using Normal.Realtime;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class ColorSyncModel
{
    [RealtimeProperty(1, true, true)]
    private Color _colorValue;


}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class ColorSyncModel : RealtimeModel {
    public UnityEngine.Color colorValue {
        get {
            return _colorValueProperty.value;
        }
        set {
            if (_colorValueProperty.value == value) return;
            _colorValueProperty.value = value;
            InvalidateReliableLength();
            FireColorValueDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(ColorSyncModel model, T value);
    public event PropertyChangedHandler<UnityEngine.Color> colorValueDidChange;
    
    public enum PropertyID : uint {
        ColorValue = 1,
    }
    
    #region Properties
    
    private ReliableProperty<UnityEngine.Color> _colorValueProperty;
    
    #endregion
    
    public ColorSyncModel() : base(null) {
        _colorValueProperty = new ReliableProperty<UnityEngine.Color>(1, _colorValue);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _colorValueProperty.UnsubscribeCallback();
    }
    
    private void FireColorValueDidChange(UnityEngine.Color value) {
        try {
            colorValueDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _colorValueProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _colorValueProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.ColorValue: {
                    changed = _colorValueProperty.Read(stream, context);
                    if (changed) FireColorValueDidChange(colorValue);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _colorValue = colorValue;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
