using Normal.Realtime;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class FloatSyncModel
{
    [RealtimeProperty(1, true, true)]
    private float _floatValue; 


}


/* ----- Begin Normal Autogenerated Code ----- */
public partial class FloatSyncModel : RealtimeModel {
    public float floatValue {
        get {
            return _floatValueProperty.value;
        }
        set {
            if (_floatValueProperty.value == value) return;
            _floatValueProperty.value = value;
            InvalidateReliableLength();
            FireFloatValueDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(FloatSyncModel model, T value);
    public event PropertyChangedHandler<float> floatValueDidChange;
    
    public enum PropertyID : uint {
        FloatValue = 1,
    }
    
    #region Properties
    
    private ReliableProperty<float> _floatValueProperty;
    
    #endregion
    
    public FloatSyncModel() : base(null) {
        _floatValueProperty = new ReliableProperty<float>(1, _floatValue);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _floatValueProperty.UnsubscribeCallback();
    }
    
    private void FireFloatValueDidChange(float value) {
        try {
            floatValueDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _floatValueProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _floatValueProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.FloatValue: {
                    changed = _floatValueProperty.Read(stream, context);
                    if (changed) FireFloatValueDidChange(floatValue);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _floatValue = floatValue;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
