using Normal.Realtime;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class IntSyncModel
{
    [RealtimeProperty(1, true, true)]
    private int _intValue;


}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class IntSyncModel : RealtimeModel {
    public int intValue {
        get {
            return _intValueProperty.value;
        }
        set {
            if (_intValueProperty.value == value) return;
            _intValueProperty.value = value;
            InvalidateReliableLength();
            FireIntValueDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(IntSyncModel model, T value);
    public event PropertyChangedHandler<int> intValueDidChange;
    
    public enum PropertyID : uint {
        IntValue = 1,
    }
    
    #region Properties
    
    private ReliableProperty<int> _intValueProperty;
    
    #endregion
    
    public IntSyncModel() : base(null) {
        _intValueProperty = new ReliableProperty<int>(1, _intValue);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _intValueProperty.UnsubscribeCallback();
    }
    
    private void FireIntValueDidChange(int value) {
        try {
            intValueDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _intValueProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _intValueProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.IntValue: {
                    changed = _intValueProperty.Read(stream, context);
                    if (changed) FireIntValueDidChange(intValue);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _intValue = intValue;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
