using Normal.Realtime;
using Normal.Realtime.Serialization;
using UnityEngine;

[RealtimeModel]
public partial class NetworkPlayerModel
{
    [RealtimeProperty(1, true, true)]
    private string _playerName;

    [RealtimeProperty(2, true, true)]
    private Color _playerColor;


}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class NetworkPlayerModel : RealtimeModel {
    public string playerName {
        get {
            return _playerNameProperty.value;
        }
        set {
            if (_playerNameProperty.value == value) return;
            _playerNameProperty.value = value;
            InvalidateReliableLength();
            FirePlayerNameDidChange(value);
        }
    }
    
    public UnityEngine.Color playerColor {
        get {
            return _playerColorProperty.value;
        }
        set {
            if (_playerColorProperty.value == value) return;
            _playerColorProperty.value = value;
            InvalidateReliableLength();
            FirePlayerColorDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(NetworkPlayerModel model, T value);
    public event PropertyChangedHandler<string> playerNameDidChange;
    public event PropertyChangedHandler<UnityEngine.Color> playerColorDidChange;
    
    public enum PropertyID : uint {
        PlayerName = 1,
        PlayerColor = 2,
    }
    
    #region Properties
    
    private ReliableProperty<string> _playerNameProperty;
    
    private ReliableProperty<UnityEngine.Color> _playerColorProperty;
    
    #endregion
    
    public NetworkPlayerModel() : base(null) {
        _playerNameProperty = new ReliableProperty<string>(1, _playerName);
        _playerColorProperty = new ReliableProperty<UnityEngine.Color>(2, _playerColor);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _playerNameProperty.UnsubscribeCallback();
        _playerColorProperty.UnsubscribeCallback();
    }
    
    private void FirePlayerNameDidChange(string value) {
        try {
            playerNameDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    private void FirePlayerColorDidChange(UnityEngine.Color value) {
        try {
            playerColorDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _playerNameProperty.WriteLength(context);
        length += _playerColorProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _playerNameProperty.Write(stream, context);
        writes |= _playerColorProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.PlayerName: {
                    changed = _playerNameProperty.Read(stream, context);
                    if (changed) FirePlayerNameDidChange(playerName);
                    break;
                }
                case (uint) PropertyID.PlayerColor: {
                    changed = _playerColorProperty.Read(stream, context);
                    if (changed) FirePlayerColorDidChange(playerColor);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _playerName = playerName;
        _playerColor = playerColor;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
